whitelist_rules:
  - closure_spacing
  - colon
  - cyclomatic_complexity
  - empty_enum_arguments
  - fatal_error_message
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - implicitly_unwrapped_optional
  - indentation
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - type_body_length
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules

excluded:
  - Pods
  - Carthage

# Rule detail settings
line_length:
  warning: 80
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 4
  error: 8

# Limit class lines between 400~600, class exceed this limit should consider separate into smaller classed
type_body_length:
  warning: 400
  error: 600

# Type name like class or struct should be 3~120
type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 120
    error: 200
  excluded: iPhone # excluded via string

# To prevent deep nested function
cyclomatic_complexity:
  warning: 4
  error: 7

file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true

identifier_name:
  min_length:
    warning: 4
    error: 2 # properties should not be named too short
  max_length:
    warning: 50 # property name should not exceed 50 charaters
    error: 51
  exclude:
    - id
    - URL

colon:
  apply_to_dictionaries: false

indentation: 2

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
